# c++ backend
FROM ubuntu:20.04

RUN apt-get update && apt-get install -y \
    git

RUN apt-get install -y \
    g++ \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .

# test compile
RUN g++ -o main main.cpp

CMD ["./main"]